# Generated by Django 3.2.11 on 2022-01-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='image',
            field=models.ImageField(default='pictures', upload_to='pics'),
            preserve_default=False,
        ),
    ]
